services:
 db:
   image: postgres
   container_name: pokerhands_db
   restart: always
   volumes:
    - pgdata:/var/lib/postgresql/data
   environment:
     POSTGRES_PASSWORD: pokerhands_password
     POSTGRES_DB: pokerhands_db
   ports:
     - 5432:5432
   logging:
     driver: json-file
     options:
       max-size: 100m
volumes:
 pgdata: